### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by Lecrapouille** [Snowapril/Deformable-Snow-Simulation#1]
Ok this is not snow but mud. Close enough ! https://www.gamasutra.com/blogs/PavelZagrebelnyy/20130613/194247/Rendering_and_simulation_in_offroad_driving_game.php

**Comment by Snowapril** [comment]
Thank you for your attention to my project! First of all, I appreciated for sharing a good reference site.
I'd also want to finish this project, but I must go to the army soon for two years because I am a south korean... It's sad but, I will set to this work when I have a spare time.

**Comment by Lecrapouille** [comment]
Sad! Good luck so :)
